export const BRAND = {
  nameAr: 'إتقان',
  nameEn: 'Itqan',
  fullNameAr: 'إتقان — المنصة التعليمية الذكية',
  fullNameEn: 'Itqan Learning Platform',
  taglineAr: 'تعلّم بعمق. طبّق بإتقان.',
  taglineEn: 'Master Skills. Build the Future.',
  shortDescriptionAr: 'المنصة التعليمية الحديثة لاكتساب المهارات والتطبيق العملي واجتياز الاختبارات بإتقان كامل.',
  shortDescriptionEn: 'The modern learning platform for mastering tech skills and hands-on application.',
  supportEmail: 'support@itqan.edu',
  domain: 'itqan.edu',
  metaTitle: 'إتقان — المنصة التعليمية الحديثة لتعليم المهارات والتطبيق',
  metaDescription: 'منصة إتقان التعليمية الحديثة: كورسات تفاعلية، اختبارات ذكية، ومسارات تعلم متطورة.',
  themeColor: '#F97316',
};
